spring:
  application:
    name: netflix-ui    
    
  datasource:
    url: jdbc:mysql://netflix-db.czscamskm91f.ap-northeast-2.rds.amazonaws.com:3306/bookdb
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect    

server:
  port: 8097
  
  
  
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka


    
logging:
  path: /tmp/thyme/logs    
      